services:
  - type: web
    name: go-score-svc
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: APP_NAME
        value: "Go Score Service"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://go-score-svc.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STDERR_FORMATTER
        value: Monolog\Formatter\JsonFormatter
      - key: SESSION_DRIVER
        value: array
      - key: CACHE_DRIVER
        value: array
      - key: QUEUE_CONNECTION
        value: sync

      # Railway MySQL Database - Actual Values
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
#      - key: DB_HOST
#        value: interchange.proxy.rlwy.net
#      - key: DB_PORT
#        value: "50689"
#      - key: DB_DATABASE
#        value: score_db
#      - key: DB_USERNAME
#        value: root
#      - key: DB_PASSWORD
#        value: NHOVSchGUzfsIIFlxFJNdpDDCsAypGib
